apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumis-ingress
  namespace: lumis
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.lumis.dev
        - api.lumis.dev
      secretName: lumis-tls
  rules:
    - host: app.lumis.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumis-web
                port:
                  number: 3000
    - host: api.lumis.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumis-api
                port:
                  number: 8000
