apiVersion: v2
name: lumis
description: AI-powered Reliability Engineering Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - sre
  - observability
  - ai
maintainers:
  - name: Horion Team
    email: engineering@horion.pro
