{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lumis.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lumis.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "lumis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "lumis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "lumis.image" (dict "root" . "repository" .Values.web.image.repository "tag" .Values.web.image.tag) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "lumis.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumis.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lumis.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "lumis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      {{- if and (eq .Values.web.service.type "NodePort") .Values.web.service.nodePort }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  type: {{ .Values.web.service.type }}
{{- end }}
